os: osx
language: objective-c
xcode_workspace: ParkRunCompanion.xcworkspace
xcode_scheme: ParkRunCompanion
xcode_destination: platform=iOS Simulator,OS=12.0, name=iPhone XR
before_install:
- brew update
install:
- brew install xcodegen
- xcodegen generate
- pod install
